// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzeZJ2YRkoPA6thfTIq33dwe5aaX51lNo',
    appId: '1:992175250211:web:86b9cf2da6df3088024a96',
    messagingSenderId: '992175250211',
    projectId: 'si-sepuh',
    authDomain: 'si-sepuh.firebaseapp.com',
    storageBucket: 'si-sepuh.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7AyZSNIbYdyDbtIDd6Ue-xMhCugIx__k',
    appId: '1:992175250211:android:2b11bd1780f889a2024a96',
    messagingSenderId: '992175250211',
    projectId: 'si-sepuh',
    storageBucket: 'si-sepuh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATuuQpO4GSpSxQjPZmPHp6R4wGFp2XhBo',
    appId: '1:992175250211:ios:00ceb8027a21455d024a96',
    messagingSenderId: '992175250211',
    projectId: 'si-sepuh',
    storageBucket: 'si-sepuh.appspot.com',
    iosBundleId: 'com.example.sisepuh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATuuQpO4GSpSxQjPZmPHp6R4wGFp2XhBo',
    appId: '1:992175250211:ios:2fe91edf0078cbeb024a96',
    messagingSenderId: '992175250211',
    projectId: 'si-sepuh',
    storageBucket: 'si-sepuh.appspot.com',
    iosBundleId: 'com.example.sisepuh.RunnerTests',
  );
}
